### ISSUE TITLE
Panasonic ac plugin

### ISSUE THREAD

**Issue by miguelsasso** [codyc1515/pagermon-rtlsdr#1]
Hi codyc1515

I am messaging you about the panasonic-ac plugin which you previously supported.  Apologies for reaching out to you via this repository, I am a github noob and couldn't find any other way to message you directly.

It appears the author which forked your plugin is no longer active.  Just wondered if you would perhaps be willing to take it back on?  :)

Many thanks

**Comment by codyc1515** [comment]
Hey. I am using Home Assistant now (via HACS).

**Comment by miguelsasso** [comment]
Ok. Do you use a Panasonic ac plugin for HA?

**Comment by codyc1515** [comment]
Yes. https://github.com/sockless-coding/panasonic_cc
